<a href="https://colab.research.google.com/github/swilsonmfc/pandas/blob/main/9_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text

![](https://i.ytimg.com/vi/95p3cVkqYHQ/hqdefault.jpg)

# Install

In [ ]:
!pip install wordcloud

Requirement already satisfied: wordcloud in /usr/local/lib/python3.7/dist-packages (1.5.0)
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python3.7/dist-packages (from wordcloud) (1.19.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from wordcloud) (7.1.2)

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk) (1.15.0)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setup

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
import glob
import json
import pprint
import string
import textwrap
from zipfile import ZipFile

import wordcloud
from collections import Counter
from collections import defaultdict

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

# Trulia Dataset

In [ ]:
!wget -O trulia.zip https://query.data.world/s/npiftlc73orgs3vrrjgvoibat4lihe
!unzip trulia.zip

--2021-08-04 17:11:18--  https://query.data.world/s/npiftlc73orgs3vrrjgvoibat4lihe
Resolving query.data.world (query.data.world)... 151.101.2.133, 151.101.66.133, 151.101.130.133, ...
Connecting to query.data.world (query.data.world)|151.101.2.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.data.world/file_download/promptcloud/trulia-property-dataset-listing/marketing_sample_for_trulia_com-trulia_property_data__20200101_20200131__5k_data.zip?auth=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcm9kLXVzZXItY2xpZW50OnN3aWxzb25tZmMiLCJpc3MiOiJhZ2VudDpzd2lsc29ubWZjOjplYTY1Mjc1ZS03ZWE5LTQ4YzctYTZiMS1kNTk0OGQ0ZTFkMzIiLCJpYXQiOjE2Mjc2NjQ3MDAsInJvbGUiOlsidXNlciIsInVzZXJfYXBpX2FkbWluIiwidXNlcl9hcGlfZW50ZXJwcmlzZV9hZG1pbiIsInVzZXJfYXBpX3JlYWQiLCJ1c2VyX2FwaV93cml0ZSJdLCJnZW5lcmFsLXB1cnBvc2UiOmZhbHNlLCJ1cmwiOiJhMzhhZjM3YzkxMzM2NTAwZWQ4YmI3MjlmNDI1OTdmZGMxMjI3MDkxIn0.2KpbDoUst7srGOgnBHxKmj41DStWdGAUWKTqIrazAkjZKMPDsdYvyQ4wMLtRHWMkNUhoK0O5DZQM1rGTQQcQEw [following]
--2021-08-04 17:11:19--  https://download.data.world/file_download/promptcloud/trulia-property-dataset-listing/marketing_sample_for_trulia_com-trulia_property_data__20200101_20200131__5k_data.zip?auth=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcm9kLXVzZXItY2xpZW50OnN3aWxzb25tZmMiLCJpc3MiOiJhZ2VudDpzd2lsc29ubWZjOjplYTY1Mjc1ZS03ZWE5LTQ4YzctYTZiMS1kNTk0OGQ0ZTFkMzIiLCJpYXQiOjE2Mjc2NjQ3MDAsInJvbGUiOlsidXNlciIsInVzZXJfYXBpX2FkbWluIiwidXNlcl9hcGlfZW50ZXJwcmlzZV9hZG1pbiIsInVzZXJfYXBpX3JlYWQiLCJ1c2VyX2FwaV93cml0ZSJdLCJnZW5lcmFsLXB1cnBvc2UiOmZhbHNlLCJ1cmwiOiJhMzhhZjM3YzkxMzM2NTAwZWQ4YmI3MjlmNDI1OTdmZGMxMjI3MDkxIn0.2KpbDoUst7srGOgnBHxKmj41DStWdGAUWKTqIrazAkjZKMPDsdYvyQ4wMLtRHWMkNUhoK0O5DZQM1rGTQQcQEw
Resolving download.data.world (download.data.world)... 151.101.2.133, 151.101.66.133, 151.101.130.133, ...
Connecting to download.data.world (download.data.world)|151.101.2.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘trulia.zip’

trulia.zip              [   <=>              ]   3.59M  5.06MB/s    in 0.7s

2021-08-04 17:11:20 (5.06 MB/s) - ‘trulia.zip’ saved [3769654]

Archive:  trulia.zip
replace marketing_sample_for_trulia_com-trulia_property_data__20200101_20200131__5k_data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: marketing_sample_for_trulia_com-trulia_property_data__20200101_20200131__5k_data.csv

In [ ]:
df = pd.read_csv('marketing_sample_for_trulia_com-trulia_property_data__20200101_20200131__5k_data.csv')
df.head()

                            Uniq Id  ...                                           Image 25
0  4bdd7a810e393f20de4392a9e46165f3  ...                                                NaN
1  08500c25a26218ffb55e3e1b76a32a17  ...  https://static.trulia-cdn.com/pictures/thumbs_...
2  4b1d8ae469c61db9906dd4a396e1cf2e  ...                                                NaN
3  c48906194e2159381dab398f6a3b1eaa  ...                                                NaN
4  dd74d7ff8f8137a1616bd20cdf6489c6  ...  https://static.trulia-cdn.com/pictures/thumbs_...

[5 rows x 68 columns]

In [ ]:
df.dtypes

Uniq Id            object
Crawl Timestamp    object
Url                object
Title              object
Description        object
                    ...
Image 21           object
Image 22           object
Image 23           object
Image 24           object
Image 25           object
Length: 68, dtype: object

In [ ]:
trulia_df = df[['Title', 
                'Description', 
                'Price', 
                'Style', 
                'Sqr Ft', 
                'Lot Size',	
                'Beds',	
                'Bath',	
                'Year Built',	
                'Price Sqr Ft',	
                'Features',	
                'Last Sold Year',
                'Last Sold For',
                'Last Tax Assestment',
                'Last Tax Year',
                'Property Type',
                'Days On Trulia',
                'City',
                'State']].copy()
trulia_df.columns = [col.lower().replace(' ', '_') for col in trulia_df.columns]

## EDA

In [ ]:
trulia_df.dtypes

title                   object
description             object
price                   object
style                   object
sqr_ft                  object
lot_size                object
beds                   float64
bath                   float64
year_built             float64
price_sqr_ft            object
features                object
last_sold_year         float64
last_sold_for           object
last_tax_assestment     object
last_tax_year          float64
property_type          float64
days_on_trulia         float64
city                    object
state                   object
dtype: object

In [ ]:
# What columns have missing values?
trulia_df.isna().sum()

title                     0
description               0
price                     0
style                   288
sqr_ft                  283
lot_size                762
beds                    335
bath                    311
year_built              500
price_sqr_ft            476
features                  0
last_sold_year         2583
last_sold_for          2583
last_tax_assestment    1915
last_tax_year          1923
property_type          5000
days_on_trulia          850
city                      0
state                     0
dtype: int64

In [ ]:
# Expand features column to look at data & patterns
trulia_df.features.str.split('|', expand=True)

                       0              1   ...    53    54
0              Townhouse      $359/sqft   ...  None  None
1                  Condo      $312/sqft   ...  None  None
2     Single Family Home      $231/sqft   ...  None  None
3     Single Family Home      $103/sqft   ...  None  None
4     Single Family Home      $140/sqft   ...  None  None
...                   ...            ...  ...   ...   ...
4995  Single Family Home       $75/sqft   ...  None  None
4996  Single Family Home       $27/sqft   ...  None  None
4997  Single Family Home      $178/sqft   ...  None  None
4998           Townhouse      $297/sqft   ...  None  None
4999               Condo    $1,889/sqft   ...  None  None

[5000 rows x 55 columns]

## Wordcloud

In [1]:
# Create a wordcloud for information in the Features Column

## Features

### Property Type

In [ ]:
# Property type
trulia_df[['property_type', 'features']]

      property_type                                           features
0               NaN  Townhouse | $359/sqft | 12 Days on Trulia | Ro...
1               NaN  Condo | $312/sqft | Lot Size: 3.23 acres | $24...
2               NaN  Single Family Home | $231/sqft | Lot Size: 3,1...
3               NaN  Single Family Home | $103/sqft | Lot Size: 6,9...
4               NaN  Single Family Home | $140/sqft | Lot Size: 689...
...             ...                                                ...
4995            NaN  Single Family Home | $75/sqft | Lot Size: 8,80...
4996            NaN  Single Family Home | $27/sqft | Lot Size: 5,61...
4997            NaN  Single Family Home | $178/sqft | Lot Size: 6,3...
4998            NaN  Townhouse | $297/sqft | 5 Days on Trulia | Gar...
4999            NaN  Condo | $1,889/sqft | Lot Size: 1 acre | $648/...

[5000 rows x 2 columns]

In [ ]:
# Use string methods accessor & split
trulia_df['feature_property_type'] = [row[0].strip() for row in trulia_df.features.str.split('|')]
trulia_df.groupby('feature_property_type').size()

feature_property_type
Apartment                17
Condo                   704
Coop                     72
Lot Land                256
Lot Size: 7296 sqft       1
Mobile Manufactured      38
Multi Family            260
Single Family Home     3202
Townhouse               448
Unknown                   2
dtype: int64

In [ ]:
trulia_df['feature_property_type'] = trulia_df.feature_property_type.replace('Lot Size: 7296 sqft', 
                                                                             'Lot Land')
trulia_df.groupby('feature_property_type').size()

feature_property_type
Apartment                17
Condo                   704
Coop                     72
Lot Land                257
Mobile Manufactured      38
Multi Family            260
Single Family Home     3202
Townhouse               448
Unknown                   2
dtype: int64

### Roof

In [ ]:
trulia_df['feature_roof'] = trulia_df.features.str.extract(r'Roof: (\w+) \|')
trulia_df['feature_roof'] = trulia_df.feature_roof.fillna('Unknown')
trulia_df.groupby('feature_roof').size()

feature_roof
Asphalt         664
Composition    1225
Metal            64
Slate            22
Tile            263
Unknown        2762
dtype: int64

### Heating

In [2]:
# Extract heating information for each property as a feature

### Cooling
* Pattern: Cooling System

In [3]:
# Extract the cooling system type as a feature

### Exterior

In [4]:
# Extract the exterior type for the property as a feature

### Stories

In [5]:
# Extract the number of stories from each property's feature list

## Numeric Types

### Days on Trulia
* Set correct type
* Impute values

In [ ]:
# Convert Days on Trulia to integer
trulia_df['feature_days_on_trulia'] = trulia_df.days_on_trulia.astype('Int64')

In [ ]:
# Assign to median (mean or 0)
trulia_df['missing_days_on_trulia'] = np.where(pd.isnull(trulia_df.feature_days_on_trulia), 1, 0)
trulia_df['feature_days_on_trulia'] = trulia_df.feature_days_on_trulia.fillna(trulia_df.feature_days_on_trulia.median())

### Beds and Bath

In [ ]:
# Convert Bath & Beds to numbers
trulia_df['beds'] = trulia_df.beds.astype(np.number)
trulia_df['bath'] = trulia_df.bath.astype(np.number)

In [ ]:
# Impute 0 Bath / Beds on Lots
# Impute Median on missing Bath / Beds for dwellings
def impute_bath_beds(row, col, impute):
  value = row[col]
  if pd.isnull(value):
    if row['feature_property_type'] == 'Lot Land':
      value = 0
    else:
      value = impute
  return value

trulia_df['feature_beds'] = trulia_df.apply(impute_bath_beds, args=('beds', trulia_df.beds.median()), axis=1)
# Create feature_bath

### Price

In [ ]:
# Helper function to clean up the currency column
def currency_cleaner(value):
  if isinstance(value, str):
    value = value.replace('$', '').replace(',', '').replace('+', '')
  return value

In [ ]:
# Remove "Contact For Estimate" rows & convert price to number
trulia_df = trulia_df[~(trulia_df.price == 'Contact For Estimate')]
trulia_df['feature_price'] = trulia_df.price.apply(currency_cleaner)
trulia_df['feature_price'] = trulia_df.feature_price.astype(np.number)

### Price per Sq Foot

In [ ]:
# Helper function to clean up the price per sqare foot
def price_cleaner(value):
  if isinstance(value, str):
    patterns = ['$', ',', '+', '/', 'sqft']
    for pattern in patterns:
      value = value.replace(pattern, '')
  return value

In [ ]:
# Price Per Square Foot
# Apply helper function
# Convert to np.number type

# Linear Regression - Price

In [ ]:
# Grab a collection of features
cols = ['feature_roof',
        'feature_days_on_trulia',
        'missing_days_on_trulia',
        'feature_beds',
        'feature_bath',
        'price_sqr_ft']

# Predict price / sqr ft on single family homes
X = trulia_df[trulia_df.feature_property_type == 'Single Family Home'][cols].copy()
X = X.dropna()
y = X.pop('price_sqr_ft')

# One hot encode object columns
X = pd.get_dummies(X, columns=['feature_roof'])

# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
# Create LinearRegression and fit on training data

In [7]:
# Use model to predict price per sq ft

In [8]:
# Compute mean absolute error

# Logistic Regression - Property Type

In [ ]:
# Run tfidf vectorizer over Trulia description corpus
tfidf = TfidfVectorizer(stop_words='english')
vecs = tfidf.fit_transform(trulia_df.description)
tfidf_df = pd.DataFrame(vecs.todense().tolist(), columns=tfidf.get_feature_names())
tfidf_df.head()

    00  000  0000  00016122030  000please  ...  âeur   â½   ââ  ââamericaã  ââs
0  0.0  0.0   0.0          0.0        0.0  ...   0.0  0.0  0.0         0.0  0.0
1  0.0  0.0   0.0          0.0        0.0  ...   0.0  0.0  0.0         0.0  0.0
2  0.0  0.0   0.0          0.0        0.0  ...   0.0  0.0  0.0         0.0  0.0
3  0.0  0.0   0.0          0.0        0.0  ...   0.0  0.0  0.0         0.0  0.0
4  0.0  0.0   0.0          0.0        0.0  ...   0.0  0.0  0.0         0.0  0.0

[5 rows x 14751 columns]

In [9]:
# Find 500 columns with the largest average TF-IDF scores

In [ ]:
# Target Variable = 1 if single family home, 0 otherwise
X = tfidf_df.copy()
y = np.where(trulia_df.feature_property_type == 'Single Family Home', 1, 0)
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [10]:
# Create a LogisticRegression

In [11]:
# Fit model to Train

In [12]:
# Predict on Test Set

In [13]:
# Compute Accuracy on Test

In [ ]:
# Baseline
# Compute a naive baseline using the ratio of Single Family Homes to total in dataset
sum(y) / len(y)

0.6350112084776849